### PR TITLE
[Hotfix] Missing err

### PR DESCRIPTION
**Pull request by loumalouomega**
Cannot compile with last master without this

### CODE REVIEW

**Comment by loumalouomega** [comment]
@LoicMarechal

**Comment by LoicMarechal** [comment]
Hi Vicente.

Thanks for pointing that out so quickly :-)
I defined the "err" at the beginning of the procedure to be consistent with the others.

Someone submitted a pull request that I accepted but it modified the master instead of the develop branch...

Regards,

Loïc

**Comment by loumalouomega** [comment]
> Hi Vicente. Thanks for pointing that out so quickly :-) I defined the "err" at the beginning of the procedure to be consistent with the others. Someone submitted a pull request that I accepted but it modified the master instead of the develop branch... Regards, Loïc

Yes, I saw, but I fixed ASAP

**Comment by loumalouomega** [comment]
> > Hi Vicente. Thanks for pointing that out so quickly :-) I defined the "err" at the beginning of the procedure to be consistent with the others. Someone submitted a pull request that I accepted but it modified the master instead of the develop branch... Regards, Loïc
> 
> Yes, I saw, but I fixed ASAP

No merge then?

**Comment by loumalouomega** [comment]
Ok, you already fixed

**Pull request closed without merging**
